version: "2"

services:
  php_app:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    volumes:
      - "./:/var/www/html"
  observable-web:
    image: openresty:dev
    ports:
      - 9145:9145
      - 8010:80
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  prometheus:
    image: prom/prometheus
    ports: 
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./docker/grafana/config.monitoring
    restart: always
  redis:
      image: redis
      ports:
        - 63790:6379

volumes:
  grafana_data: